// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// extract_dbl
SEXP extract_dbl(SEXP xptr, size_t j, ListOf<IntegerVector> list_ind_row);
RcppExport SEXP _bigdfr_extract_dbl(SEXP xptrSEXP, SEXP jSEXP, SEXP list_ind_rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type list_ind_row(list_ind_rowSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_dbl(xptr, j, list_ind_row));
    return rcpp_result_gen;
END_RCPP
}
// extract_int
SEXP extract_int(SEXP xptr, size_t j, ListOf<IntegerVector> list_ind_row);
RcppExport SEXP _bigdfr_extract_int(SEXP xptrSEXP, SEXP jSEXP, SEXP list_ind_rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type list_ind_row(list_ind_rowSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_int(xptr, j, list_ind_row));
    return rcpp_result_gen;
END_RCPP
}
// extract_lgl
SEXP extract_lgl(SEXP xptr, size_t j, ListOf<IntegerVector> list_ind_row);
RcppExport SEXP _bigdfr_extract_lgl(SEXP xptrSEXP, SEXP jSEXP, SEXP list_ind_rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type list_ind_row(list_ind_rowSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_lgl(xptr, j, list_ind_row));
    return rcpp_result_gen;
END_RCPP
}
// extract_ushort
SEXP extract_ushort(SEXP xptr, size_t j, ListOf<IntegerVector> list_ind_row);
RcppExport SEXP _bigdfr_extract_ushort(SEXP xptrSEXP, SEXP jSEXP, SEXP list_ind_rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type list_ind_row(list_ind_rowSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_ushort(xptr, j, list_ind_row));
    return rcpp_result_gen;
END_RCPP
}
// extract_string
List extract_string(SEXP xptr, size_t j, ListOf<IntegerVector> list_ind_row, CharacterVector strings);
RcppExport SEXP _bigdfr_extract_string(SEXP xptrSEXP, SEXP jSEXP, SEXP list_ind_rowSEXP, SEXP stringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type list_ind_row(list_ind_rowSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strings(stringsSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_string(xptr, j, list_ind_row, strings));
    return rcpp_result_gen;
END_RCPP
}
// fill_dbl
void fill_dbl(Environment X, size_t j, SEXP vec);
RcppExport SEXP _bigdfr_fill_dbl(SEXP XSEXP, SEXP jSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type X(XSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vec(vecSEXP);
    fill_dbl(X, j, vec);
    return R_NilValue;
END_RCPP
}
// fill_int
void fill_int(Environment X, size_t j, SEXP vec);
RcppExport SEXP _bigdfr_fill_int(SEXP XSEXP, SEXP jSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type X(XSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vec(vecSEXP);
    fill_int(X, j, vec);
    return R_NilValue;
END_RCPP
}
// fill_lgl
void fill_lgl(Environment X, size_t j, SEXP vec);
RcppExport SEXP _bigdfr_fill_lgl(SEXP XSEXP, SEXP jSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type X(XSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vec(vecSEXP);
    fill_lgl(X, j, vec);
    return R_NilValue;
END_RCPP
}
// fill_ushort
void fill_ushort(Environment X, size_t j, SEXP vec);
RcppExport SEXP _bigdfr_fill_ushort(SEXP XSEXP, SEXP jSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type X(XSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vec(vecSEXP);
    fill_ushort(X, j, vec);
    return R_NilValue;
END_RCPP
}
// getXPtrFDF
SEXP getXPtrFDF(std::string path, size_t n_all, IntegerVector types);
RcppExport SEXP _bigdfr_getXPtrFDF(SEXP pathSEXP, SEXP n_allSEXP, SEXP typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_all(n_allSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type types(typesSEXP);
    rcpp_result_gen = Rcpp::wrap(getXPtrFDF(path, n_all, types));
    return rcpp_result_gen;
END_RCPP
}
// add_bytes
void add_bytes(std::string fileName, std::size_t nbyte);
RcppExport SEXP _bigdfr_add_bytes(SEXP fileNameSEXP, SEXP nbyteSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type nbyte(nbyteSEXP);
    add_bytes(fileName, nbyte);
    return R_NilValue;
END_RCPP
}
// rel_to_abs
void rel_to_abs(ListOf<IntegerVector> list_ind_row, ListOf<IntegerVector> list_ind, IntegerVector sizes);
RcppExport SEXP _bigdfr_rel_to_abs(SEXP list_ind_rowSEXP, SEXP list_indSEXP, SEXP sizesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type list_ind_row(list_ind_rowSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type list_ind(list_indSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sizes(sizesSEXP);
    rel_to_abs(list_ind_row, list_ind, sizes);
    return R_NilValue;
END_RCPP
}
// NA_to_0
IntegerVector NA_to_0(SEXP x_);
RcppExport SEXP _bigdfr_NA_to_0(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(NA_to_0(x_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bigdfr_extract_dbl", (DL_FUNC) &_bigdfr_extract_dbl, 3},
    {"_bigdfr_extract_int", (DL_FUNC) &_bigdfr_extract_int, 3},
    {"_bigdfr_extract_lgl", (DL_FUNC) &_bigdfr_extract_lgl, 3},
    {"_bigdfr_extract_ushort", (DL_FUNC) &_bigdfr_extract_ushort, 3},
    {"_bigdfr_extract_string", (DL_FUNC) &_bigdfr_extract_string, 4},
    {"_bigdfr_fill_dbl", (DL_FUNC) &_bigdfr_fill_dbl, 3},
    {"_bigdfr_fill_int", (DL_FUNC) &_bigdfr_fill_int, 3},
    {"_bigdfr_fill_lgl", (DL_FUNC) &_bigdfr_fill_lgl, 3},
    {"_bigdfr_fill_ushort", (DL_FUNC) &_bigdfr_fill_ushort, 3},
    {"_bigdfr_getXPtrFDF", (DL_FUNC) &_bigdfr_getXPtrFDF, 3},
    {"_bigdfr_add_bytes", (DL_FUNC) &_bigdfr_add_bytes, 2},
    {"_bigdfr_rel_to_abs", (DL_FUNC) &_bigdfr_rel_to_abs, 3},
    {"_bigdfr_NA_to_0", (DL_FUNC) &_bigdfr_NA_to_0, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_bigdfr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
