# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getXPtrFDF <- function(path, n, ind_row, types) {
    .Call(`_bigdfr_getXPtrFDF`, path, n, ind_row, types)
}

add_bytes <- function(fileName, nbyte) {
    invisible(.Call(`_bigdfr_add_bytes`, fileName, nbyte))
}

