# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_dbl <- function(xptr, j) {
    .Call(`_bigdfr_extract_dbl`, xptr, j)
}

extract_int <- function(xptr, j) {
    .Call(`_bigdfr_extract_int`, xptr, j)
}

extract_lgl <- function(xptr, j) {
    .Call(`_bigdfr_extract_lgl`, xptr, j)
}

extract_ushort <- function(xptr, j) {
    .Call(`_bigdfr_extract_ushort`, xptr, j)
}

extract_string <- function(xptr, j, strings) {
    .Call(`_bigdfr_extract_string`, xptr, j, strings)
}

fill_dbl <- function(xptr, j, vec) {
    invisible(.Call(`_bigdfr_fill_dbl`, xptr, j, vec))
}

fill_int <- function(xptr, j, vec) {
    invisible(.Call(`_bigdfr_fill_int`, xptr, j, vec))
}

fill_lgl <- function(xptr, j, vec) {
    invisible(.Call(`_bigdfr_fill_lgl`, xptr, j, vec))
}

fill_ushort <- function(xptr, j, vec) {
    invisible(.Call(`_bigdfr_fill_ushort`, xptr, j, vec))
}

getXPtrFDF <- function(path, n, ind_row, types) {
    .Call(`_bigdfr_getXPtrFDF`, path, n, ind_row, types)
}

add_bytes <- function(fileName, nbyte) {
    invisible(.Call(`_bigdfr_add_bytes`, fileName, nbyte))
}

NA_replace <- function(x, by = 0L) {
    .Call(`_bigdfr_NA_replace`, x, by)
}

